name: Slither Analysis

on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Set up Node
        uses: actions/setup-node@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v15

      - name: Configure Cachix
        uses: cachix/cachix-action@v10
        with:
            name: dapp

      - name: Install and make
        run: nix-shell --run 'make'

      - name: Build the contracts
        run: nix-shell --run 'dapp build'

      - name: Run Slither
        uses: crytic/slither-action@v0.1.0
        with:
            ignore-compile: true